services:
  gateway:
    build: ..
    runtime: nvidia
    environment:
      - NVIDIA_DISABLE_REQUIRE=1
      - EIG_PORT=8008
      - EIG_HTTP_PORT=8080
    ports:
      - "8008:8008"
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2g
    restart: unless-stopped
