models:
  - id: "mobilenet_v2_cls"
    engine: "models/mobilenetv2_fp32.plan"
    input:
      layout: "NCHW"
      dtype:  "fp32"
      shape:  [1, 3, 224, 224]
    outputs:
      - name: "logits"   # [1,1000]
