name: ci

on:
  push:
  pull_request:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq cmake ninja-build clang clang-tidy libyaml-cpp-dev

      - name: Configure (CI mode: server off)
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DEIG_BUILD_SERVER=OFF -DEIG_BUILD_CLIENT_CPP=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build
        run: cmake --build build -j

      - name: Run clang-tidy
        run: |
          python3 - <<'PY'
          import json, subprocess, os, sys
          db=json.load(open('build/compile_commands.json'))
          files=[c['file'] for c in db if any(x in c['file'] for x in ['src','include','clients/cpp'])]
          if not files: sys.exit(0)
          bad=0
          for f in files:
            cmd=['clang-tidy','-p','build',f]
            print('TIDY',f)
            r=subprocess.run(cmd)
            if r.returncode!=0: bad=1
          sys.exit(bad)
          PY
